# Generated by Django 5.2 on 2025-05-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tugas', models.CharField(max_length=200, verbose_name='Nama Tugas')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi Tugas')),
                ('prioritas', models.CharField(choices=[('rendah', 'Rendah'), ('sedang', 'Sedang'), ('tinggi', 'Tinggi')], default='sedang', max_length=10, verbose_name='Prioritas')),
                ('tenggat_waktu', models.DateTimeField(blank=True, null=True, verbose_name='Tenggat Waktu')),
                ('list_kegiatan_tugas', models.JSONField(blank=True, default=list, verbose_name='List Kegiatan Tugas')),
                ('link_pendukung', models.JSONField(blank=True, default=list, verbose_name='Link Pendukung')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tugas',
                'verbose_name_plural': 'Tugas',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
