# Generated by Django 5.2 on 2025-05-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='list_kegiatan_tugas_status',
            field=models.JSONField(blank=True, default=list, verbose_name='Status Setiap Kegiatan Tugas'),
        ),
        migrations.AddField(
            model_name='task',
            name='status_kegiatan',
            field=models.CharField(choices=[('pending', 'Tertunda'), ('on_going', 'Sedang Dikerjakan'), ('complete', 'Selesai')], default='pending', max_length=20, verbose_name='Status Kegiatan'),
        ),
    ]
